[book]
authors = ["Shunsuke Shibayama"]
# language = "en"
multilingual = true
src = "syntax"
title = "The Erg Book"

# [build]
# build-dir = "docs"

[output.html]
additional-css = [
    "theme/css/error.css",
]
additional-js = [
    "theme/js/lz-string.min.js",
]
